auth:
  - user: foo
    group: foo
    uid: 1000
    gid: 1000
    password: bar
  - user: yyy
    group: xxx
    uid: 1100
    gid: 1200
    password_file: /tmp/yyy_password

global:
  - "force user = foo"
  - "force group = foo"

share:
  - name: public
    comment: Public
    path: /samba/public
    browsable: ${BROWSABLE}
    readonly: yes
    guestok: yes
    validusers: ""
    adminusers: ""
    writelist: ""
    veto: no
  - name: share
    path: /samba/share
    browsable: ${BROWSABLE}
    readonly: no
    guestok: yes
    writelist: foo
    veto: no
  - name: foo
    path: /samba/foo
    browsable: ${BROWSABLE}
    readonly: no
    guestok: no
    validusers: foo
    writelist: foo
    veto: no
    hidefiles: /_*/
