apiVersion: v1
kind: ConfigMap
metadata:
  name: smb-config-yml
  labels:
  {{- include "samba.labels" . | nindent 4 }}
data:
  config.yml: |
    auth:
    {{- range $value := $.Values.configMap.auth }}
    - user: {{ $value.user }}
      group: {{ $value.group }}
      uid: {{ $value.uid }}
      gid: {{ $value.gid }}
      password: {{ $value.password }}
    {{- end }}
    {{- if .Values.configMap.share }}
    share:
    {{- toYaml .Values.configMap.share | nindent 4 }}
    {{- end }}
    {{- if .Values.configMap.global }}
    global:
    {{- range $.Values.configMap.global }}
    - {{ . -}}
    {{ end }}
    {{ end }}
