apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "samba.name" . }}-data
spec:
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName -}}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}